apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::267834697821:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-AU4Xihttsroe
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::267834697821:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::267834697821:user/Ramesh
      username: Ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-10T08:57:52Z"
  name: aws-auth
  namespace: kube-system
  uid: 292074be-ced4-473f-88ba-71395bfa61e6
