apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::717892306043:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-LyLfzBAbarc1
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::717892306043:user/suresh
      username: suresh 
kind: ConfigMap    
metadata:
  creationTimestamp: "2026-03-10T05:32:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1125"
  uid: 47436fe5-c3b5-408e-a9cd-9074b984e54d
