apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::267834697821:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-xDy1bNuOWAk8
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::267834697821:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-01T06:21:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1199"
  uid:  571d9ad7-21c9-4f13-9f35-1f35a53bef2c
