apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::267834697821:role/eksctl-roboshop-dev-addon-iamserviceaccount-r-Role1-NcklQ9CtKgtG
  creationTimestamp: "2026-06-15T10:22:31Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: secret-reader
  namespace: roboshop
  resourceVersion: "7530"
  uid: 2864b5a8-aef8-4d8e-a7e2-47af23aef283
